In [1]:
import pandas as pd

In [5]:
df = pd.read_csv('./juggle_data.csv')

In [6]:
df

      大当り回数   種類     時間    ゲーム  獲得数  台 番     日期        更新日期        数据日期
0       NaN  NaN    NaN    NaN  NaN  640  Day 1  2024-10-03  2024-10-02
1        --   --     --   44.0   --  640  Day 1  2024-10-03  2024-10-02
2        51   BB  22:49   32.0  240  640  Day 1  2024-10-03  2024-10-02
3        --   RB  22:46   40.0   96  640  Day 1  2024-10-03  2024-10-02
4        50   BB  22:42  312.0  240  640  Day 1  2024-10-03  2024-10-02
...     ...  ...    ...    ...  ...  ...    ...         ...         ...
10240     2   BB  19:44  498.0  240  728  Day 7  2024-10-03  2024-09-26
10241    --   RB  12:23  135.0   96  728  Day 7  2024-10-03  2024-09-26
10242    --   RB  12:13  100.0   97  728  Day 7  2024-10-03  2024-09-26
10243     1   BB  12:05    1.0  240  728  Day 7  2024-10-03  2024-09-26
10244    --   RB  12:04  299.0   97  728  Day 7  2024-10-03  2024-09-26

[10245 rows x 9 columns]

In [7]:
list(set(df['台 番'].tolist()))

[640,
 641,
 642,
 643,
 644,
 645,
 667,
 668,
 669,
 670,
 671,
 672,
 673,
 674,
 675,
 676,
 677,
 678,
 679,
 680,
 694,
 695,
 696,
 697,
 698,
 699,
 700,
 701,
 702,
 703,
 704,
 705,
 706,
 707,
 721,
 722,
 723,
 724,
 725,
 726,
 727,
 728]

In [12]:
df[df['日期']== 'Day 1']

      大当り回数   種類     時間    ゲーム  獲得数  台 番     日期        更新日期        数据日期
0       NaN  NaN    NaN    NaN  NaN  640  Day 1  2024-10-03  2024-10-02
1        --   --     --   44.0   --  640  Day 1  2024-10-03  2024-10-02
2        51   BB  22:49   32.0  240  640  Day 1  2024-10-03  2024-10-02
3        --   RB  22:46   40.0   96  640  Day 1  2024-10-03  2024-10-02
4        50   BB  22:42  312.0  240  640  Day 1  2024-10-03  2024-10-02
...     ...  ...    ...    ...  ...  ...    ...         ...         ...
10071     4   BB  14:01  226.0  240  728  Day 1  2024-10-03  2024-10-02
10072     3   BB  13:44   28.0  240  728  Day 1  2024-10-03  2024-10-02
10073     2   BB  13:40  327.0  240  728  Day 1  2024-10-03  2024-10-02
10074    --   RB  10:52  188.0   98  728  Day 1  2024-10-03  2024-10-02
10075     1   BB  10:38   49.0  240  728  Day 1  2024-10-03  2024-10-02

[1530 rows x 9 columns]

In [78]:
df = df.dropna()

In [79]:
# df_game_sum = df.groupby(['台 番','日期'])['ゲーム'].sum().reset_index()
# df_game_sum_over_5t = df_game_sum[df_game_sum['ゲーム']>=5000]

In [80]:
df = df[::-1]
df_0 = df[['ゲーム', '台 番', '日期']]
df_0.columns = ['game', 'no', 'date']
df_0 = df_0.reset_index(drop=True)


def check_condition(group):
    condition = (group['game'].shift(-1) < 100) & \
                (group['game'].shift(-2) < 100) & \
                (group['game'].shift(-3) < 100)
    
    same_group = (group['no'] == group['no'].shift(-1)) & \
                 (group['no'] == group['no'].shift(-2)) & \
                 (group['no'] == group['no'].shift(-3)) & \
                 (group['date'] == group['date'].shift(-1)) & \
                 (group['date'] == group['date'].shift(-2)) & \
                 (group['date'] == group['date'].shift(-3))
    
    return condition & same_group


df_0['target'] = df_0.groupby(['no', 'date']).apply(check_condition).reset_index(level=[0,1], drop=True)
# df_0['target'] = df_0['target'].astype(int)
df_0['target_1'] = df_0['target'].shift(1)
df_0[:40]
# df_0['target'] = df_0['target'].astype(int)
# df_0['target_1'] = df_0['target_1'].astype(int)
# df_0[(df_0['target'] == True )&(df_0['target'] == False )]
df_0 = df_0.dropna()

df_0['target'] = df_0['target'].apply(lambda x:int(x))
df_0['target_1'] = df_0['target_1'].apply(lambda x:int(x))

/var/folders/cp/047kqs6x43q8fvchrym7q84h0000gn/T/ipykernel_25766/364305647.py:22: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_0['target'] = df_0.groupby(['no', 'date']).apply(check_condition).reset_index(level=[0,1], drop=True)

In [81]:
df_1  = df_0[(df_0['target']==1)&(df_0['target_1']==0)]
df_1['target_0'] = 1
df_1

/var/folders/cp/047kqs6x43q8fvchrym7q84h0000gn/T/ipykernel_25766/814906578.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_1['target_0'] = 1

       game   no   date  target  target_1  target_0
13    102.0  640  Day 1       1         0         1
22    103.0  640  Day 1       1         0         1
32    158.0  640  Day 1       1         0         1
39    166.0  640  Day 1       1         0         1
43    148.0  640  Day 1       1         0         1
...     ...  ...    ...     ...       ...       ...
9887  611.0  728  Day 5       1         0         1
9893  106.0  728  Day 6       1         0         1
9907  303.0  728  Day 6       1         0         1
9914  194.0  728  Day 6       1         0         1
9927  130.0  728  Day 6       1         0         1

[594 rows x 6 columns]

In [82]:
df_2 = df_0[['game','no','date']].join(df_1[['game','no','date','target_0']].set_index(['game','no','date']),on=['game','no','date'],how='left')

In [83]:
df_2['target_0'] = df_2['target_0'].fillna(0)

In [84]:
df_2['target_0'].value_counts()

target_0
0.0    9308
1.0     654
Name: count, dtype: int64

In [85]:
df_2

       game   no   date  target_0
1      32.0  640  Day 1       0.0
2      40.0  640  Day 1       0.0
3     312.0  640  Day 1       0.0
4      25.0  640  Day 1       0.0
5      11.0  640  Day 1       0.0
...     ...  ...    ...       ...
9946  498.0  728  Day 7       0.0
9947  135.0  728  Day 7       0.0
9948  100.0  728  Day 7       0.0
9949    1.0  728  Day 7       0.0
9950  299.0  728  Day 7       0.0

[9962 rows x 4 columns]

In [86]:
df_2[:50]

     game   no   date  target_0
1    32.0  640  Day 1       0.0
2    40.0  640  Day 1       0.0
3   312.0  640  Day 1       0.0
4    25.0  640  Day 1       0.0
5    11.0  640  Day 1       0.0
6   106.0  640  Day 1       0.0
7   136.0  640  Day 1       0.0
8   145.0  640  Day 1       0.0
9    75.0  640  Day 1       0.0
10  200.0  640  Day 1       0.0
11   65.0  640  Day 1       0.0
12   19.0  640  Day 1       0.0
13  102.0  640  Day 1       1.0
13  102.0  640  Day 1       1.0
14   25.0  640  Day 1       0.0
15   32.0  640  Day 1       0.0
16    7.0  640  Day 1       0.0
17  148.0  640  Day 1       1.0
18   83.0  640  Day 1       0.0
19   21.0  640  Day 1       0.0
20  455.0  640  Day 1       0.0
21    7.0  640  Day 1       0.0
22  103.0  640  Day 1       1.0
23   81.0  640  Day 1       0.0
24   86.0  640  Day 1       0.0
25   15.0  640  Day 1       0.0
26   55.0  640  Day 1       0.0
27   44.0  640  Day 1       0.0
28  295.0  640  Day 1       0.0
29  288.0  640  Day 1       0.0
30  109.0  640  Day 1       0.0
31  118.0  640  Day 1       0.0
32  158.0  640  Day 1       1.0
33   80.0  640  Day 1       0.0
34   78.0  640  Day 1       0.0
35    4.0  640  Day 1       0.0
36   29.0  640  Day 1       0.0
37  112.0  640  Day 1       0.0
38  292.0  640  Day 1       0.0
39  166.0  640  Day 1       1.0
40   16.0  640  Day 1       0.0
41   41.0  640  Day 1       0.0
42   44.0  640  Day 1       0.0
43  148.0  640  Day 1       1.0
44   12.0  640  Day 1       0.0
45    8.0  640  Day 1       0.0
46    4.0  640  Day 1       0.0
47  143.0  640  Day 1       0.0
48   51.0  640  Day 1       0.0
49  156.0  640  Day 1       0.0

In [97]:
df_2[:500].to_csv('test.csv')

In [98]:
df = df_2.copy()